[package]
name = "repdet-ciph"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.32.5"
rand = "0.8.5"
structopt = "0.3.26"
